### PR TITLE
Fix - Delete streams where the video is not given anymore

### LINKED ISSUE #79: If scheduled stream is "abandoned" it stays on the homepage but should be archived or removed.
@christophrumpel You had a stream scheduled for yesterday, but never went live. So i stayed on the homepage. This could possibly happen to anyone. So i think this might be something to think about. 

We could check this in the `CheckIfUpcomingStreamsAreLiveCommand`; maybe limit this to 3 hours in the past to limit the amount of request to youtube every 5 minutes? (I don't know if you worry about the api requests?) 

Maybe we should also archive the streams after some time? (3 hours or a day or something)

What do you think?

### PR DESCRIPTION
**Pull request by christophrumpel**
This PR fixes #79.

I think this task should be in the `UpdateUpcomingStreamsCommand` because this is responsible for checking upcoming streams. I adapted the command (similar to the `UpdateLiveAndFinishedStreamsCommand`) so that we can handle streams where there is no response from Youtube anymore.

Can you take a look @spaantje?

### CODE REVIEW

File: app/Console/Commands/UpdateUpcomingStreamsCommand.php [hunk 1]
```diff
@@ -29,21 +30,33 @@ public function handle(): int
...
-                    'scheduled_start_time' => $streamData->plannedStart,
-                    'status' => $streamData->status,
-                ]))
-            ->filter()
-            ->count();
-
-        $this->info($updatesCount.' stream(s) were updated.');
+        $youtubeResponse = Youtube::videos($streams->keys());
+
+        $streams->map(function (Stream $stream) use ($youtubeResponse) {
```
Comment (spaantje) [inline app/Console/Commands/UpdateUpcomingStreamsCommand.php:35]: maybe use each instead of map because where not mapping anymore?

**Review by spaantje — COMMENTED** [review]
Looks great 👍
